### ISSUE TITLE
Convenience method for cancelling repeated tasks

### ISSUE THREAD

**Issue by florianreinhart** [swift-server/swift-service-lifecycle#59]
LifecycleNIOCompat could provide a convenience method to cancel scheduled `RepeatedTask`s. I came up with the following extension:

```swift
extension LifecycleHandler {
    public static func cancelRepeatedTask(_ task: RepeatedTask, on eventLoopGroup: EventLoopGroup) -> LifecycleHandler {
        return self.eventLoopFuture {
            let promise = eventLoopGroup.next().makePromise(of: Void.self)
            task.cancel(promise: promise)
            return promise.futureResult
        }
    }
}
```

What do you think? I am happy to create a PR for this.

**Comment by ktoso** [comment]
That could be useful and could live in the compat lib indeed.

Hmm, I sanity checked the ordering of cancelations and seems to be fine. If the task already had a `cancellationPromise` it'll be completed first, and then the `localCancellationPromise` (the `promise` here) will be, so that seems good.

Would you say this API should accept an EL rather than an ELG since we just use an EL anyway and this way we make it usable easier if one just has a specific EL in hand?

WDYT about this in general @Lukasa ?

**Comment by florianreinhart** [comment]
Using an EL is a good idea. Even better would be using the associated EL of the task, but that's not public (probably for good reason?).

**Comment by Lukasa** [comment]
Yeah, just accepting the `EL` is fine.

There’s no good reason for us not to make the `EL` of the task public. We already make the `EL` of futures public, so we clearly aren’t too motivated to hide this.

**Comment by ktoso** [comment]
Would you mind sending in a PR for this @florianreinhart ?
